# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0877e4bdbef59b1770f971a855b92e8b9dba12cd59f05a7590245ee16e7f4b35544d1645b9f152fd58faef168e51ebcf5cb39676415adbbcaab696c5e9092d6
  facebook_key: defb48cef205287c0f67ef8b34c9bbec
  facebook_secret: a26b8049c1675018d02cd47349247e09
  facebook_app_id: 632581560192667
test:
  secret_key_base: 941d68d3dde92d6487b8b8210061c7786fb946031ef5c23c149016b68ee5011dbe71746523cdd99b7dc1a8a933c2b2ebdc6143281ade4c13cd96cd919b5a8ea6
  facebook_key: defb48cef205287c0f67ef8b34c9bbec
  facebook_secret: c4ad79176bf500b0b8fb6cb5103d5eb2
  facebook_app_id: 632574623526694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
